-- ============================================================================
-- OC Public Services Platform — Database Schema
-- Target: Oracle Autonomous Database 23ai (Always Free)
-- Run as ADMIN user
-- ============================================================================

-- Schema
CREATE USER ocpublic IDENTIFIED BY "<password>";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO ocpublic;
ALTER USER ocpublic DEFAULT TABLESPACE DATA;

-- ============================================================================
-- Tables
-- ============================================================================

-- Data sources registry
CREATE TABLE ocpublic.datasets (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    source_url  VARCHAR2(500),
    contact_org VARCHAR2(200),
    collection_date     DATE,
    update_frequency    VARCHAR2(50),
    last_updated        DATE DEFAULT SYSDATE,
    created_at          DATE DEFAULT SYSDATE
);

-- Documents with vector embeddings (RAG storage)
CREATE TABLE ocpublic.documents (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id  NUMBER REFERENCES ocpublic.datasets(id),
    content     CLOB NOT NULL,
    embedding   VECTOR(384, FLOAT32),
    source_name VARCHAR2(200),
    source_url  VARCHAR2(500),
    last_updated DATE DEFAULT SYSDATE,
    created_at  DATE DEFAULT SYSDATE
);

-- Anonymized query logs (no PII)
CREATE TABLE ocpublic.query_logs (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_hash  VARCHAR2(64),
    confidence  VARCHAR2(20),
    response_time_ms NUMBER,
    created_at  DATE DEFAULT SYSDATE
);

-- User feedback
CREATE TABLE ocpublic.feedback (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query       VARCHAR2(2000),
    helpful     CHAR(1) CHECK (helpful IN ('Y', 'N')),
    comment     VARCHAR2(2000),
    created_at  DATE DEFAULT SYSDATE
);

-- Public alerts
CREATE TABLE ocpublic.alerts (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(500) NOT NULL,
    description CLOB,
    severity    VARCHAR2(20) DEFAULT 'info',
    status      VARCHAR2(20) DEFAULT 'ACTIVE',
    source_name VARCHAR2(200),
    created_at  DATE DEFAULT SYSDATE,
    updated_at  DATE DEFAULT SYSDATE
);

-- ============================================================================
-- Vector Index (for RAG similarity search)
-- ============================================================================
-- Must be run AFTER data is loaded:
-- CREATE VECTOR INDEX doc_embedding_idx ON ocpublic.documents(embedding)
--     ORGANIZATION NEIGHBOR PARTITIONS
--     DISTANCE COSINE
--     WITH TARGET ACCURACY 95;
